name: time-series
channels:
    - defaults
    - pytorch
    - conda-forge
dependencies:
    - seaborn
    - matplotlib
    - numpy
    - pytorch=1.11.0
    - torchtext
    - torchmetrics
    - cudatoolkit=11.3
    - jupyterlab
    - ipywidgets
    - pip
    - pip:
        - pytorch-common==0.0.19